### PR TITLE
Add new crypto icons

### PR DESCRIPTION
**Pull request by pruchay**
I want to add icons that don't exist in this cool repository.

### CODE REVIEW

**Comment by monzanifabio** [comment]
Hi @pruchay thanks for the contributions! :)

**Review by monzanifabio — CHANGES_REQUESTED** [review]
All icons should have a 1:1 aspect ratio and the artboard be 500px x 500px

**Comment by pruchay** [comment]
Is it better now?

**Review by monzanifabio — APPROVED** [review]
Thanks for the quick changes

**Comment by monzanifabio** [comment]
Added AAVE, AVAX, CREAM, CRV, DOT, IRIS, KSM, LTO, NEAR, PERL, SOL, SRM, SUSHI, SXP, UMA, UNI, VITE

**Pull request merged**
